name: Quarkus SSE Server

run-name: ${{ github.actor }} is building Quarkus SSE Server 🚀

on: [push, pull_request]

jobs:
  Quarkus-Native-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Native Image
        uses: docker://quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
        with:
          args: |
            /bin/bash -c "./mvnw package -Pnative"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sse-server
          path: target/*-runner

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
