name: Quarkus SSE Server

run-name: ${{ github.actor }} is building Quarkus SSE Server 🚀

on: [push, pull_request]

jobs:
  Quarkus-Native-Build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Native Image
      run: ./mvnw package -Pnative

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sse-server
        path: target/*-runner